---
- name: Clone a VM from a template in Proxmox
  hosts: localhost
  gather_facts: false
  vars:
    proxmox_host: "your-proxmox-server-ip"
    proxmox_user: "your-proxmox-username@pam!your-token-id"
    proxmox_password: "your-token-secret"
    node: "proxmox-node-name"
    template: "debian-12-template"
    new_vm_id: 110
    new_vm_name: "new-debian-vm"
    target_storage: "local-lvm"
    cpu_cores: 2
    memory_mb: 2048
    disk_size_gb: 20

  tasks:
    - name: Clone the template
      uri:
        url: "https://{{ proxmox_host }}/api2/json/nodes/{{ node }}/qemu/{{ template }}/clone"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        body:
          newid: "{{ new_vm_id }}"
          name: "{{ new_vm_name }}"
          target: "{{ target_storage }}"
        body_format: form-urlencoded
        user: "{{ proxmox_user }}"
        password: "{{ proxmox_password }}"
        validate_certs: false
      register: clone_result

    - name: Set resources for the new VM
      uri:
        url: "https://{{ proxmox_host }}/api2/json/nodes/{{ node }}/qemu/{{ new_vm_id }}/config"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        body:
          cores: "{{ cpu_cores }}"
          memory: "{{ memory_mb }}"
          disksize: "{{ disk_size_gb }}G"
        body_format: form-urlencoded
        user: "{{ proxmox_user }}"
        password: "{{ proxmox_password }}"
        validate_certs: false

    - name: Start the new VM
      uri:
        url: "https://{{ proxmox_host }}/api2/json/nodes/{{ node }}/qemu/{{ new_vm_id }}/status/start"
        method: POST
        user: "{{ proxmox_user }}"
        password: "{{ proxmox_password }}"
        validate_certs: false

